project_id = "ktmqwhkywxogxktuqcfx"

[functions.create-checkout]
verify_jwt = true

[functions.shipping]
verify_jwt = true

[functions.send-email]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
